# Generated by Django 2.2.6 on 2019-11-06 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemCode', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='상품코드')),
                ('itemName', models.CharField(max_length=100, verbose_name='상품명')),
                ('imageUrl', models.URLField(verbose_name='이미지 url')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.CreateModel(
            name='StyleShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(verbose_name='이미지 url')),
                ('author', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('items', models.ManyToManyField(to='api.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LookBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnrImageUrl', models.URLField(verbose_name='배너 이미지 url')),
                ('mainImageUrl', models.URLField(verbose_name='LookBook 대표 이미지 url')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('items', models.ManyToManyField(to='api.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
