# Generated by Django 2.2.6 on 2019-11-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_styleshare_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleshare',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='api.Item'),
        ),
    ]
