# Generated by Django 2.2.6 on 2019-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='StyleShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지 url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, null=True, to='item.Item')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='styleshare.Tag')),
            ],
            options={
                'db_table': 'styleshare',
                'ordering': ['-created_at'],
            },
        ),
    ]
