# Generated by Django 2.2.6 on 2019-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnr_image_url', models.URLField(verbose_name='배너 이미지 url')),
                ('main_image_url', models.URLField(verbose_name='LookBook 대표 이미지 url')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='item.Item')),
            ],
            options={
                'db_table': 'magazines',
                'ordering': ['-created_at'],
            },
        ),
    ]
