# Generated by Django 2.2.6 on 2019-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_content_type'),
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='items',
            field=models.ManyToManyField(to='item.Item'),
        ),
    ]
