# Generated by Django 2.2.6 on 2020-01-14 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='상품코드')),
                ('item_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('image_url', models.URLField(verbose_name='이미지 url')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
            },
        ),
    ]
