# Generated by Django 2.2.6 on 2019-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='상품코드')),
                ('item_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('image_url', models.URLField(verbose_name='이미지 url')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
            },
        ),
    ]
