# Generated by Django 2.2.6 on 2019-11-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='object_id',
        ),
    ]
